// <auto-generated />
using System;
using CucinaMammaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CucinaMammaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250304114104_Fix_ForeignKey_SottoCategorie")]
    partial class Fix_ForeignKey_SottoCategorie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CucinaMammaAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Commento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Commenti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.FatteDaVoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("FatteDaVoi");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Immagine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int?>("FatteDaVoiId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFileSeo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PassaggioPreparazioneId")
                        .HasColumnType("int");

                    b.Property<int?>("RicettaId")
                        .HasColumnType("int");

                    b.Property<int?>("SottoCategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FatteDaVoiId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("PassaggioPreparazioneId");

                    b.HasIndex("RicettaId");

                    b.HasIndex("SottoCategoriaId");

                    b.ToTable("Immagini");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ingredienti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.PassaggioPreparazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ImmagineId")
                        .HasColumnType("int");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImmagineId");

                    b.HasIndex("RicettaId", "Ordine")
                        .IsUnique();

                    b.ToTable("PassaggiPreparazione");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RegistroAttivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccessoSospetto")
                        .HasColumnType("bit");

                    b.Property<int>("Azione")
                        .HasColumnType("int");

                    b.Property<string>("Browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dispositivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndirizzoIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeRicetta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RicettaId")
                        .HasColumnType("int");

                    b.Property<bool>("TentativoFallito")
                        .HasColumnType("bit");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("registroAttivitas");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Ricetta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPubblicazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficolta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempoPreparazione")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Ricette");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaCategoria", b =>
                {
                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("RicettaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("RicetteCategorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaIngrediente", b =>
                {
                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RicettaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("RicettaIngredienti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaPreferita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSalvataggio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RicettaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("RicettePreferite");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaSottoCategoria", b =>
                {
                    b.Property<int>("RicettaId")
                        .HasColumnType("int");

                    b.Property<int>("SottoCategoriaId")
                        .HasColumnType("int");

                    b.HasKey("RicettaId", "SottoCategoriaId");

                    b.HasIndex("SottoCategoriaId");

                    b.ToTable("RicetteSottoCategorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.SottoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SottoCategorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.ThemeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThemeSettings");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVerificata")
                        .HasColumnType("bit");

                    b.Property<string>("FotoProfiloUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenScadenza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.UtenteSocialLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCollegamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("UtentiSocialLogin");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Commento", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("Commenti")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.FatteDaVoi", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("ImmaginiFatteDaVoi")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Immagine", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Categoria", "Categoria")
                        .WithMany("Immagini")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CucinaMammaAPI.Models.FatteDaVoi", "FatteDaVoi")
                        .WithMany("Immagini")
                        .HasForeignKey("FatteDaVoiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CucinaMammaAPI.Models.Ingrediente", "Ingrediente")
                        .WithMany("Immagini")
                        .HasForeignKey("IngredienteId");

                    b.HasOne("CucinaMammaAPI.Models.PassaggioPreparazione", "PassaggioPreparazione")
                        .WithMany("Immagini")
                        .HasForeignKey("PassaggioPreparazioneId");

                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("Immagini")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CucinaMammaAPI.Models.SottoCategoria", "SottoCategoria")
                        .WithMany("Immagini")
                        .HasForeignKey("SottoCategoriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Categoria");

                    b.Navigation("FatteDaVoi");

                    b.Navigation("Ingrediente");

                    b.Navigation("PassaggioPreparazione");

                    b.Navigation("Ricetta");

                    b.Navigation("SottoCategoria");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.PassaggioPreparazione", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Immagine", "Immagine")
                        .WithMany()
                        .HasForeignKey("ImmagineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("PassaggiPreparazione")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Immagine");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RegistroAttivita", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ricetta", null)
                        .WithMany("RegistriAttivita")
                        .HasForeignKey("RicettaId");

                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany("RegistriAttivita")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Ricetta", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany("RicetteCreate")
                        .HasForeignKey("UtenteId");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaCategoria", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Categoria", "Categoria")
                        .WithMany("RicetteCategorie")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("RicetteCategorie")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaIngrediente", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ingrediente", "Ingrediente")
                        .WithMany("RicettaIngredienti")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("RicettaIngredienti")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Ricetta");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaPreferita", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("SalvataDaUtenti")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany("RicettePreferite")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.RicettaSottoCategoria", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Ricetta", "Ricetta")
                        .WithMany("RicetteSottoCategorie")
                        .HasForeignKey("RicettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CucinaMammaAPI.Models.SottoCategoria", "SottoCategoria")
                        .WithMany("RicetteSottoCategorie")
                        .HasForeignKey("SottoCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ricetta");

                    b.Navigation("SottoCategoria");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.SottoCategoria", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Categoria", "Categoria")
                        .WithMany("SottoCategorie")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.UtenteSocialLogin", b =>
                {
                    b.HasOne("CucinaMammaAPI.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Categoria", b =>
                {
                    b.Navigation("Immagini");

                    b.Navigation("RicetteCategorie");

                    b.Navigation("SottoCategorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.FatteDaVoi", b =>
                {
                    b.Navigation("Immagini");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Ingrediente", b =>
                {
                    b.Navigation("Immagini");

                    b.Navigation("RicettaIngredienti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.PassaggioPreparazione", b =>
                {
                    b.Navigation("Immagini");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Ricetta", b =>
                {
                    b.Navigation("Commenti");

                    b.Navigation("Immagini");

                    b.Navigation("ImmaginiFatteDaVoi");

                    b.Navigation("PassaggiPreparazione");

                    b.Navigation("RegistriAttivita");

                    b.Navigation("RicettaIngredienti");

                    b.Navigation("RicetteCategorie");

                    b.Navigation("RicetteSottoCategorie");

                    b.Navigation("SalvataDaUtenti");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.SottoCategoria", b =>
                {
                    b.Navigation("Immagini");

                    b.Navigation("RicetteSottoCategorie");
                });

            modelBuilder.Entity("CucinaMammaAPI.Models.Utente", b =>
                {
                    b.Navigation("RegistriAttivita");

                    b.Navigation("RicetteCreate");

                    b.Navigation("RicettePreferite");
                });
#pragma warning restore 612, 618
        }
    }
}
